In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [2]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
print(len(words))
print(max(len(w) for w in words))
print(words[:8])

32033
15
['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']


In [3]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
vocab_size = len(itos)
print(itos)
print(vocab_size)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}
27


In [4]:
# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?

def build_dataset(words):  
  X, Y = [], []
  
  for w in words:
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y

import random
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))

Xtr,  Ytr  = build_dataset(words[:n1])     # 80%
Xdev, Ydev = build_dataset(words[n1:n2])   # 10%
Xte,  Yte  = build_dataset(words[n2:])     # 10%

torch.Size([182625, 3]) torch.Size([182625])
torch.Size([22655, 3]) torch.Size([22655])
torch.Size([22866, 3]) torch.Size([22866])


In [5]:
# utility function we will use later when comparing manual gradients to PyTorch gradients
def cmp(s, dt, t):
  ex = torch.all(dt == t.grad).item()
  app = torch.allclose(dt, t.grad)
  maxdiff = (dt - t.grad).abs().max().item()
  print(f'{s:15s} | exact: {str(ex):5s} | approximate: {str(app):5s} | maxdiff: {maxdiff}')

In [6]:
n_embd = 10 # the dimensionality of the character embedding vectors
n_hidden = 64 # the number of neurons in the hidden layer of the MLP

g = torch.Generator().manual_seed(2147483647) # for reproducibility
C  = torch.randn((vocab_size, n_embd),            generator=g)
# Layer 1
W1 = torch.randn((n_embd * block_size, n_hidden), generator=g) * (5/3)/((n_embd * block_size)**0.5)
b1 = torch.randn(n_hidden,                        generator=g) * 0.1 # using b1 just for fun, it's useless because of BN
# Layer 2
W2 = torch.randn((n_hidden, vocab_size),          generator=g) * 0.1
b2 = torch.randn(vocab_size,                      generator=g) * 0.1
# BatchNorm parameters
bngain = torch.randn((1, n_hidden))*0.1 + 1.0
bnbias = torch.randn((1, n_hidden))*0.1

# Note: I am initializating many of these parameters in non-standard ways
# because sometimes initializating with e.g. all zeros could mask an incorrect
# implementation of the backward pass.

parameters = [C, W1, b1, W2, b2, bngain, bnbias]
print(sum(p.nelement() for p in parameters)) # number of parameters in total
for p in parameters:
  p.requires_grad = True

4137


In [7]:
batch_size = 32
n = batch_size # a shorter variable also, for convenience
# construct a minibatch
ix = torch.randint(0, Xtr.shape[0], (batch_size,), generator=g)
Xb, Yb = Xtr[ix], Ytr[ix] # batch X,Y

In [8]:
# forward pass, "chunkated" into smaller steps that are possible to backward one at a time

emb = C[Xb] # embed the characters into vectors
embcat = emb.view(emb.shape[0], -1) # concatenate the vectors
# Linear layer 1
hprebn = embcat @ W1 + b1 # hidden layer pre-activation
# BatchNorm layer
bnmeani = 1/n*hprebn.sum(0, keepdim=True)
bndiff = hprebn - bnmeani
bndiff2 = bndiff**2
bnvar = 1/(n-1)*(bndiff2).sum(0, keepdim=True) # note: Bessel's correction (dividing by n-1, not n)
bnvar_inv = (bnvar + 1e-5)**-0.5
bnraw = bndiff * bnvar_inv
hpreact = bngain * bnraw + bnbias
# Non-linearity
h = torch.tanh(hpreact) # hidden layer
# Linear layer 2
logits = h @ W2 + b2 # output layer
# cross entropy loss (same as F.cross_entropy(logits, Yb))
logit_maxes = logits.max(1, keepdim=True).values
norm_logits = logits - logit_maxes # subtract max for numerical stability
counts = norm_logits.exp()
counts_sum = counts.sum(1, keepdims=True)
counts_sum_inv = counts_sum**-1 # if I use (1.0 / counts_sum) instead then I can't get backprop to be bit exact...
probs = counts * counts_sum_inv
logprobs = probs.log()
loss = -logprobs[range(n), Yb].mean()

# PyTorch backward pass
for p in parameters:
  p.grad = None
for t in [logprobs, probs, counts, counts_sum, counts_sum_inv, # afaik there is no cleaner way
          norm_logits, logit_maxes, logits, h, hpreact, bnraw,
         bnvar_inv, bnvar, bndiff2, bndiff, hprebn, bnmeani,
         embcat, emb]:
  t.retain_grad()
loss.backward()
loss

tensor(3.3390, grad_fn=<NegBackward0>)

In [9]:
logprobs[range(n)].shape, logprobs[range(n)]

(torch.Size([32, 27]),
 tensor([[-2.7014, -2.4817, -3.9915, -2.9118, -3.9038, -2.5258, -3.6007, -3.2637,
          -3.9269, -3.4777, -3.2829, -3.3038, -3.2816, -3.5045, -3.4553, -4.3187,
          -4.7335, -3.9371, -4.1697, -2.9211, -3.0176, -3.8755, -3.6935, -2.5567,
          -2.8598, -3.6871, -3.8497],
         [-2.9303, -2.8797, -2.4326, -2.8539, -3.2855, -3.3005, -3.9704, -3.0994,
          -3.8292, -3.7310, -2.9420, -3.1105, -3.1436, -3.5209, -3.0645, -3.2504,
          -3.6350, -4.0844, -3.9040, -3.4409, -3.9747, -3.8770, -4.3407, -2.6424,
          -3.7022, -3.3207, -3.6607],
         [-4.0226, -3.7113, -4.2520, -4.2274, -3.7668, -3.1186, -2.6889, -2.8739,
          -2.8136, -3.4965, -3.8312, -3.3322, -3.1222, -2.9991, -3.8627, -3.6193,
          -4.3266, -3.4233, -3.5865, -2.2730, -2.7595, -3.3092, -3.2443, -3.1995,
          -3.1487, -3.9406, -3.5355],
         [-3.5084, -3.6161, -3.2272, -2.8739, -2.7549, -3.4570, -3.0599, -3.1999,
          -2.9283, -3.9868, -3.2112, -3.707

In [10]:
logprobs.shape, logprobs

(torch.Size([32, 27]),
 tensor([[-2.7014, -2.4817, -3.9915, -2.9118, -3.9038, -2.5258, -3.6007, -3.2637,
          -3.9269, -3.4777, -3.2829, -3.3038, -3.2816, -3.5045, -3.4553, -4.3187,
          -4.7335, -3.9371, -4.1697, -2.9211, -3.0176, -3.8755, -3.6935, -2.5567,
          -2.8598, -3.6871, -3.8497],
         [-2.9303, -2.8797, -2.4326, -2.8539, -3.2855, -3.3005, -3.9704, -3.0994,
          -3.8292, -3.7310, -2.9420, -3.1105, -3.1436, -3.5209, -3.0645, -3.2504,
          -3.6350, -4.0844, -3.9040, -3.4409, -3.9747, -3.8770, -4.3407, -2.6424,
          -3.7022, -3.3207, -3.6607],
         [-4.0226, -3.7113, -4.2520, -4.2274, -3.7668, -3.1186, -2.6889, -2.8739,
          -2.8136, -3.4965, -3.8312, -3.3322, -3.1222, -2.9991, -3.8627, -3.6193,
          -4.3266, -3.4233, -3.5865, -2.2730, -2.7595, -3.3092, -3.2443, -3.1995,
          -3.1487, -3.9406, -3.5355],
         [-3.5084, -3.6161, -3.2272, -2.8739, -2.7549, -3.4570, -3.0599, -3.1999,
          -2.9283, -3.9868, -3.2112, -3.707

In [11]:
Yb.shape, Yb

(torch.Size([32]),
 tensor([ 8, 14, 15, 22,  0, 19,  9, 14,  5,  1, 20,  3,  8, 14, 12,  0, 11,  0,
         26,  9, 25,  0,  1,  1,  7, 18,  9,  3,  5,  9,  0, 18]))

In [12]:
logprobs[range(n), Yb].shape, logprobs[range(n), Yb]

(torch.Size([32]),
 tensor([-3.9269, -3.0645, -3.6193, -3.3869, -4.1794, -3.5248, -3.0863, -4.0139,
         -3.2054, -4.1721, -3.1366, -1.6348, -2.7481, -3.0293, -2.9908, -3.1885,
         -3.8768, -3.0283, -3.5732, -3.3694, -2.9139, -3.0263, -4.2186, -3.9437,
         -3.4912, -2.9152, -2.9778, -3.8520, -2.7933, -3.4684, -3.3309, -3.1617],
        grad_fn=<IndexBackward0>))

In [13]:
# Exercise 1: backprop through the whole thing manually, 
# backpropagating through exactly all of the variables 
# as they are defined in the forward pass above, one by one

dlogprobs = torch.zeros_like(logprobs) 
'''
for example mean of a, b, c is
mean = (a + b + c) / 3 (NLL)
loss = -(a + b + c) / 3
loss = -1/3a + -1/3b + -1/3c
dloss/da = -1/3
dloss/db = -1/3
dloss/dc = -1/3

Therefore, generally dloss/da = -1/n
'''
'''
Additionaly we can see that logprobs is [32x27] and Yb is [32].
But in loss we are not taking account of other values of logprobs and shrinking it to Yb i.e 32. So what happens to gradient of other 
values of logprobs?
Well they don't matter as they don't contribute to the loss.
'''
dlogprobs[range(n), Yb] = -1.0/n #(Derivate of -logprobs[range(n), Yb].mean())
dprobs = (1.0 / probs) * dlogprobs 


cmp('logprobs', dlogprobs, logprobs)
# cmp('probs', dprobs, probs)
# cmp('counts_sum_inv', dcounts_sum_inv, counts_sum_inv)
# cmp('counts_sum', dcounts_sum, counts_sum)
# cmp('counts', dcounts, counts)
# cmp('norm_logits', dnorm_logits, norm_logits)
# cmp('logit_maxes', dlogit_maxes, logit_maxes)
# cmp('logits', dlogits, logits)
# cmp('h', dh, h)
# cmp('W2', dW2, W2)
# cmp('b2', db2, b2)
# cmp('hpreact', dhpreact, hpreact)
# cmp('bngain', dbngain, bngain)
# cmp('bnbias', dbnbias, bnbias)
# cmp('bnraw', dbnraw, bnraw)
# cmp('bnvar_inv', dbnvar_inv, bnvar_inv)
# cmp('bnvar', dbnvar, bnvar)
# cmp('bndiff2', dbndiff2, bndiff2)
# cmp('bndiff', dbndiff, bndiff)
# cmp('bnmeani', dbnmeani, bnmeani)
# cmp('hprebn', dhprebn, hprebn)
# cmp('embcat', dembcat, embcat)
# cmp('W1', dW1, W1)
# cmp('b1', db1, b1)
# cmp('emb', demb, emb)
# cmp('C', dC, C)

logprobs        | exact: True  | approximate: True  | maxdiff: 0.0
