In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open("names.txt", "r").read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [15]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [38]:
block_size = 3
X, Y = [], []
for w in words[:5]:
    context = [0]*block_size
    for ch in w+'.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]
X = torch.tensor(X)
Y = torch.tensor(Y)
X, Y

(tensor([[ 0,  0,  0],
         [ 0,  0,  5],
         [ 0,  5, 13],
         [ 5, 13, 13],
         [13, 13,  1],
         [ 0,  0,  0],
         [ 0,  0, 15],
         [ 0, 15, 12],
         [15, 12,  9],
         [12,  9, 22],
         [ 9, 22,  9],
         [22,  9,  1],
         [ 0,  0,  0],
         [ 0,  0,  1],
         [ 0,  1, 22],
         [ 1, 22,  1],
         [ 0,  0,  0],
         [ 0,  0,  9],
         [ 0,  9, 19],
         [ 9, 19,  1],
         [19,  1,  2],
         [ 1,  2,  5],
         [ 2,  5, 12],
         [ 5, 12, 12],
         [12, 12,  1],
         [ 0,  0,  0],
         [ 0,  0, 19],
         [ 0, 19, 15],
         [19, 15, 16],
         [15, 16,  8],
         [16,  8,  9],
         [ 8,  9,  1]]),
 tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
          1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0]))

In [64]:
X.shape, Y.shape, X.dtype, Y.dtype

(torch.Size([32, 3]), torch.Size([32]), torch.int64, torch.int64)

In [67]:
C = torch.randn((27,2))

In [68]:
C

tensor([[-2.1591, -0.0756],
        [-0.6354, -0.5881],
        [-0.0224,  0.3820],
        [-0.2976, -0.1694],
        [ 1.3370, -1.1938],
        [ 0.0332, -0.0343],
        [ 0.2145, -0.8159],
        [ 1.4054, -0.7887],
        [-0.0834,  2.0421],
        [ 0.0304,  1.2032],
        [ 0.1439,  1.2806],
        [-0.2863,  1.6762],
        [ 0.0686,  0.3424],
        [ 0.2426,  1.2569],
        [-0.2809, -1.8066],
        [ 0.1636,  0.3836],
        [-0.7958, -0.4244],
        [ 1.6010,  0.8750],
        [-2.1613, -0.8232],
        [ 0.0081, -0.9123],
        [ 0.9008, -1.8191],
        [-1.0657,  0.9307],
        [-0.6154, -2.5418],
        [ 0.8559,  0.5844],
        [-1.8400,  0.1015],
        [-1.8779,  0.6478],
        [ 0.2249,  0.1427]])

In [81]:
emb = C[X]
emb.shape, emb

(torch.Size([32, 3, 2]),
 tensor([[[-2.1591, -0.0756],
          [-2.1591, -0.0756],
          [-2.1591, -0.0756]],
 
         [[-2.1591, -0.0756],
          [-2.1591, -0.0756],
          [ 0.0332, -0.0343]],
 
         [[-2.1591, -0.0756],
          [ 0.0332, -0.0343],
          [ 0.2426,  1.2569]],
 
         [[ 0.0332, -0.0343],
          [ 0.2426,  1.2569],
          [ 0.2426,  1.2569]],
 
         [[ 0.2426,  1.2569],
          [ 0.2426,  1.2569],
          [-0.6354, -0.5881]],
 
         [[-2.1591, -0.0756],
          [-2.1591, -0.0756],
          [-2.1591, -0.0756]],
 
         [[-2.1591, -0.0756],
          [-2.1591, -0.0756],
          [ 0.1636,  0.3836]],
 
         [[-2.1591, -0.0756],
          [ 0.1636,  0.3836],
          [ 0.0686,  0.3424]],
 
         [[ 0.1636,  0.3836],
          [ 0.0686,  0.3424],
          [ 0.0304,  1.2032]],
 
         [[ 0.0686,  0.3424],
          [ 0.0304,  1.2032],
          [-0.6154, -2.5418]],
 
         [[ 0.0304,  1.2032],
          [-0.6