In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open("names.txt", "r").read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [5]:
block_size = 3
X, Y = [], []
for w in words[:5]:
    context = [0]*block_size
    for ch in w+'.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]
X = torch.tensor(X)
Y = torch.tensor(Y)
X, Y

(tensor([[ 0,  0,  0],
         [ 0,  0,  5],
         [ 0,  5, 13],
         [ 5, 13, 13],
         [13, 13,  1],
         [ 0,  0,  0],
         [ 0,  0, 15],
         [ 0, 15, 12],
         [15, 12,  9],
         [12,  9, 22],
         [ 9, 22,  9],
         [22,  9,  1],
         [ 0,  0,  0],
         [ 0,  0,  1],
         [ 0,  1, 22],
         [ 1, 22,  1],
         [ 0,  0,  0],
         [ 0,  0,  9],
         [ 0,  9, 19],
         [ 9, 19,  1],
         [19,  1,  2],
         [ 1,  2,  5],
         [ 2,  5, 12],
         [ 5, 12, 12],
         [12, 12,  1],
         [ 0,  0,  0],
         [ 0,  0, 19],
         [ 0, 19, 15],
         [19, 15, 16],
         [15, 16,  8],
         [16,  8,  9],
         [ 8,  9,  1]]),
 tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
          1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0]))

In [6]:
X.shape, Y.shape, X.dtype, Y.dtype

(torch.Size([32, 3]), torch.Size([32]), torch.int64, torch.int64)

In [7]:
C = torch.randn((27,2))

In [8]:
C

tensor([[-1.7420,  1.4020],
        [-0.2300, -0.4950],
        [ 0.4954,  0.3850],
        [ 0.4717, -1.3112],
        [ 0.5573, -0.7186],
        [-0.7635,  0.4223],
        [-1.8353, -1.2933],
        [ 1.2059, -1.4008],
        [-0.5531, -0.7053],
        [-0.7553, -1.3448],
        [ 1.2876,  1.0932],
        [ 0.7668, -0.2078],
        [ 0.1897,  1.6719],
        [ 0.9076, -0.6886],
        [ 1.4464, -0.2366],
        [ 0.4161, -0.2882],
        [ 0.3232,  1.0323],
        [-0.3653,  0.2720],
        [ 1.5304, -0.8151],
        [ 0.0960,  0.3321],
        [ 1.4336,  0.1962],
        [-2.2178,  0.5528],
        [-0.8506,  1.1200],
        [-1.1165, -0.5208],
        [-0.4158,  0.0659],
        [-1.8557,  1.2911],
        [-0.8943, -0.8668]])

In [9]:
# Create embedding matrix
emb = C[X]
emb.shape, emb

(torch.Size([32, 3, 2]),
 tensor([[[-1.7420,  1.4020],
          [-1.7420,  1.4020],
          [-1.7420,  1.4020]],
 
         [[-1.7420,  1.4020],
          [-1.7420,  1.4020],
          [-0.7635,  0.4223]],
 
         [[-1.7420,  1.4020],
          [-0.7635,  0.4223],
          [ 0.9076, -0.6886]],
 
         [[-0.7635,  0.4223],
          [ 0.9076, -0.6886],
          [ 0.9076, -0.6886]],
 
         [[ 0.9076, -0.6886],
          [ 0.9076, -0.6886],
          [-0.2300, -0.4950]],
 
         [[-1.7420,  1.4020],
          [-1.7420,  1.4020],
          [-1.7420,  1.4020]],
 
         [[-1.7420,  1.4020],
          [-1.7420,  1.4020],
          [ 0.4161, -0.2882]],
 
         [[-1.7420,  1.4020],
          [ 0.4161, -0.2882],
          [ 0.1897,  1.6719]],
 
         [[ 0.4161, -0.2882],
          [ 0.1897,  1.6719],
          [-0.7553, -1.3448]],
 
         [[ 0.1897,  1.6719],
          [-0.7553, -1.3448],
          [-0.8506,  1.1200]],
 
         [[-0.7553, -1.3448],
          [-0.8

In [12]:
X[13], C[X][13]

(tensor([0, 0, 1]),
 tensor([[-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.2300, -0.4950]]))

In [14]:
#Randomly initialized weights and biases
W1 = torch.randn((6, 100))
b1 = torch.randn(100)
W1, b1

(tensor([[-0.5394, -0.6147,  0.0316, -0.2055,  0.1993, -0.0935, -0.9306, -0.7493,
          -2.2087,  1.0324,  1.2198, -1.1996,  0.7869, -0.1540, -1.6660,  0.3867,
          -0.4527, -0.7049, -1.6179, -1.7732,  1.0061,  0.5348, -0.3137,  0.4364,
          -0.4962,  1.6743, -0.2202, -1.1451, -0.3874, -0.4601,  0.0736, -0.3902,
           0.4710, -0.7395, -0.3943,  0.2420, -0.5568, -0.4236,  0.1582,  0.2149,
           0.2591,  1.1098,  1.9753,  1.0986,  0.0065, -0.0239, -0.6852, -0.1071,
          -1.3501,  1.1936,  0.3413, -0.8965, -1.5036,  0.1129,  1.3717, -1.6917,
          -1.3425, -0.2785,  0.4911,  0.2785,  0.1357, -0.6746, -1.7251,  0.3667,
           3.2040, -1.4828, -0.0453,  1.5101, -0.1833, -1.1133,  0.8091,  0.1163,
           1.1542, -0.9709,  1.3458,  0.6276,  0.9580,  0.0066,  0.9063, -0.0762,
          -1.0078, -0.4574, -0.6292, -0.1965, -2.0233,  0.0264,  0.9327, -0.8434,
          -0.8583,  0.4383, -0.4126, -1.3698, -1.0923, -0.3226,  0.0200, -0.3484,
           0.953

In [15]:
W1.shape, b1.shape

(torch.Size([6, 100]), torch.Size([100]))

In [17]:
# 3 Input nueron example
emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]

(tensor([[-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.7635,  0.4223],
         [ 0.9076, -0.6886],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [ 0.4161, -0.2882],
         [ 0.1897,  1.6719],
         [-0.7553, -1.3448],
         [-0.8506,  1.1200],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.2300, -0.4950],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.7553, -1.3448],
         [ 0.0960,  0.3321],
         [-0.2300, -0.4950],
         [ 0.4954,  0.3850],
         [-0.7635,  0.4223],
         [ 0.1897,  1.6719],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [ 0.0960,  0.3321],
         [ 0.4161, -0.2882],
         [ 0.3232,  1.0323],
         [-0.5531, -0.7053]]),
 tensor([[-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0

In [19]:
# Concatinating the second dimension of each to match Weight Matrix W1's dimensions
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1)

tensor([[-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.7635,  0.4223],
        [-1.7420,  1.4020, -0.7635,  0.4223,  0.9076, -0.6886],
        [-0.7635,  0.4223,  0.9076, -0.6886,  0.9076, -0.6886],
        [ 0.9076, -0.6886,  0.9076, -0.6886, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020,  0.4161, -0.2882],
        [-1.7420,  1.4020,  0.4161, -0.2882,  0.1897,  1.6719],
        [ 0.4161, -0.2882,  0.1897,  1.6719, -0.7553, -1.3448],
        [ 0.1897,  1.6719, -0.7553, -1.3448, -0.8506,  1.1200],
        [-0.7553, -1.3448, -0.8506,  1.1200, -0.7553, -1.3448],
        [-0.8506,  1.1200, -0.7553, -1.3448, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.2300, -0.4950],
        [-1.7420,  1.4020, -0.2300, -0.4950, -0.8506,  1.1200],
        [-0.2300, -0.4950, -0.8506,  1.1

In [20]:
# Example of torch.unbind
torch.unbind(emb, 1)

(tensor([[-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.7635,  0.4223],
         [ 0.9076, -0.6886],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [ 0.4161, -0.2882],
         [ 0.1897,  1.6719],
         [-0.7553, -1.3448],
         [-0.8506,  1.1200],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.2300, -0.4950],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0.7553, -1.3448],
         [ 0.0960,  0.3321],
         [-0.2300, -0.4950],
         [ 0.4954,  0.3850],
         [-0.7635,  0.4223],
         [ 0.1897,  1.6719],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [ 0.0960,  0.3321],
         [ 0.4161, -0.2882],
         [ 0.3232,  1.0323],
         [-0.5531, -0.7053]]),
 tensor([[-1.7420,  1.4020],
         [-1.7420,  1.4020],
         [-0

In [24]:
# Using cat and unvind together to avoid hardcoding dimensions and match emb and W1's dimensions
torch.cat(torch.unbind(emb , 1), 1)
# Output is same as torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1) but neurons and dimensions are not hard-coded, therefore is better for variable block_size

tensor([[-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.7635,  0.4223],
        [-1.7420,  1.4020, -0.7635,  0.4223,  0.9076, -0.6886],
        [-0.7635,  0.4223,  0.9076, -0.6886,  0.9076, -0.6886],
        [ 0.9076, -0.6886,  0.9076, -0.6886, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020,  0.4161, -0.2882],
        [-1.7420,  1.4020,  0.4161, -0.2882,  0.1897,  1.6719],
        [ 0.4161, -0.2882,  0.1897,  1.6719, -0.7553, -1.3448],
        [ 0.1897,  1.6719, -0.7553, -1.3448, -0.8506,  1.1200],
        [-0.7553, -1.3448, -0.8506,  1.1200, -0.7553, -1.3448],
        [-0.8506,  1.1200, -0.7553, -1.3448, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.2300, -0.4950],
        [-1.7420,  1.4020, -0.2300, -0.4950, -0.8506,  1.1200],
        [-0.2300, -0.4950, -0.8506,  1.1

In [22]:
# Efficient way is to use torch.view instead of cat and/or unbind
emb.view(emb.shape[0], 6)
# Output is same as torch.cat(torch.unbind(emb , 1), 1) but is much more efficient than cat as .view() manipulates 'storage' component of neurons instead of creating new neurons

tensor([[-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.7635,  0.4223],
        [-1.7420,  1.4020, -0.7635,  0.4223,  0.9076, -0.6886],
        [-0.7635,  0.4223,  0.9076, -0.6886,  0.9076, -0.6886],
        [ 0.9076, -0.6886,  0.9076, -0.6886, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020,  0.4161, -0.2882],
        [-1.7420,  1.4020,  0.4161, -0.2882,  0.1897,  1.6719],
        [ 0.4161, -0.2882,  0.1897,  1.6719, -0.7553, -1.3448],
        [ 0.1897,  1.6719, -0.7553, -1.3448, -0.8506,  1.1200],
        [-0.7553, -1.3448, -0.8506,  1.1200, -0.7553, -1.3448],
        [-0.8506,  1.1200, -0.7553, -1.3448, -0.2300, -0.4950],
        [-1.7420,  1.4020, -1.7420,  1.4020, -1.7420,  1.4020],
        [-1.7420,  1.4020, -1.7420,  1.4020, -0.2300, -0.4950],
        [-1.7420,  1.4020, -0.2300, -0.4950, -0.8506,  1.1200],
        [-0.2300, -0.4950, -0.8506,  1.1

In [25]:
# Creating second layer of NN 
h = torch.tanh(emb.view(emb.shape[0], 6) @ W1 + b1)
h, h.shape

(tensor([[-0.8956,  0.9024,  0.9965,  ..., -1.0000, -0.2833,  0.9097],
         [-0.9882,  0.9869,  0.6460,  ..., -1.0000, -0.7331,  0.9544],
         [-0.9747,  0.9971, -0.9989,  ..., -0.9997, -0.1188, -0.5962],
         ...,
         [-0.9987,  0.1622,  0.9288,  ..., -0.9847, -0.2392,  0.9679],
         [-0.9993,  0.9703,  0.5753,  ..., -0.9924,  0.6781,  0.1950],
         [-0.9420, -0.1723,  0.4745,  ..., -0.9792,  0.9248, -0.3226]]),
 torch.Size([32, 100]))